RAID = [
    "TERI AMMY KE BHOXDE KO JALTE HUYE KOYLE PE SHEK KE PELUNGA - 🖤👅👌",
    "TERE BAAP KO BICH SADAK PE GIRA GIRA KR MARUNGA AUR LAST ME USKE MUH PE MOOT KAR JAUNGA 🤣🤣👌🖤",
    "BHAINS JAISI AMMY KE AULAAD SALE LODU JAISE SHAKAL KE 🤣🤣",
    "TERI BHEN KO USKE COLLEGE KE LIBRARY ME HI CHOD KE PREGNANT KARDUNGA LODU 👻🤣🤣🤣😈👅",
    "TERI BHEN KE MUH ME LODA DAL KE USSE PAPA BULWAUNGA KHUD KO 👅😈",
    "TERI BHEN KO JHULE PE BAITHA KE USKI CHUT PE APNA GARAM LODA TOUCH KARUNGA 🤣👻",
    "TERI AMMY KA ENC0UNTER KAR DUNGA PRIYANKA  READY KE BALAT KARIYON KI TARAH 🤣",
    "TERI AMMA KA BHOSDA MEI BULDOSER LEKE GHUS JAUNGA 😈🤣👀👅",
    "CHUP KAR RANDI PUTRA CHINNAL KE AULAAD 🤣",
    "TERI BHEN KE BHOSDE ME @ITZ_HARPREET_07 KA LODA😂",
    "TERI MA TOH MERA KABJE MAI HAI LENE CHATA HAI TOH PAY 3 LAKH..🤩👊👤😍",
    "TERI BHEN KA BHOSDA 😂 TERI BHEN MARGAYI💥🔥🔥",
    "TERI MA KA BHOSDA ME @ITZ_DEVIL_XD KA LODA😂🔥",
    "TERI BHEN MEREKO PAPA BOLTE HAI👿😎👊",
    "SAB LOG BOLTE ARUN OP BOLTE 😈🤩🔥",
    "ARUN PAPA 👅YE NAM YAD RAKHNA KID🤩",
    "ARUN KA PIRO BOT SE CHOD JAYEGA LODE😂👿😳",
    "TEREKO APNA BHEN CHAIYE OK DEDUNGA PAR PAISA DENE PADEGA😈👅",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍",
    "TERE BAAP XAKKA MADARCHOD USKI MA KI BUR ME USKI GAND  MARVA DUNGA",
    "AUR 9 MAHINE TERI MA KI CHOOT SE FIR SE EK TERE JAISE SUAR PAIDA HOGA😹",
    "AAJ PARTY ME AANA MAT BHULNA RANDI KI AULAD! MUNNILALSAAALEE MADARCHOD TERI MA KO CHODDUUU 😍😛",
    "GANDU MERE SADKE PAIDA HUE KIDE TERI BHEN K BUR ME🗣️",
    "AUR TERI BEHEN JO HAMARE PYAASE LAND KI DEEWANI HAI USKE TOH MUH ME HI 🖕💥",
    "SAALI SUWAR KA LAND ITNA CHUUSI HAI KI DOOR SE MANO SUWARO KA TOLI AARAHA HO",
    "BHEN KI LAUDI KO KUTTO AUR SUWARO KA TOLI SE CHUDWA 🙊😂💋",
    "GAAND MAAR K LAND MUH SE NIKAL DENGE TERI MA KA CHUT KA CHUTAMBAR FAD DALENGE",
    "TERI MA KI CHUT KO FAAD K USME SUWAAR KA PESAAD DAALKAR SAALI K CHUT PE LAAT SE DULATTI MAAR KAR 🤣😅",
    "TERI AMMY ⚫ KE G🍑ND KO MUKKA MARKE TOD DUNGA MADAR FATHER 🍑🤣 BAAP SE BAKCHODI😂",
    "TERI AMMY KA ASIQ HUN WO V KHUFIYA ASIQ ATI HAI MUJHSE CHUMMIYA LENE APNE CHO00T🤣",
    "G@ND MEI RERE SUA GHUSA KE SWETTER BNA DUNGA 😂😗",
    "JIJA SE BKCH0DI KARTA HAI MADERCH0D TAMIZ SIKH LOWDE ⚫🤣",
    "BHOS@DI KE AISA THAPPAD MARUNGA TERE MUH KE DANT GAD SE HOKER GIRENGE 🤣🤣🤣🤣🤣🤓",
    "G@ND KE BAWASIR ME LAGNE WALA KIDA HAI TU G@NDU 🤣",
    "TU LADCHATTE KAHI KE BAAP SE LADNE AAYA HAI AAUKAD HAI TERI MA KA BHOXDA 🤣",
    "HAHAHA 🤣 GANDU TERA BAAL PAKAD KE DIWAL SE LADA LADA KE TERA  SEER PHOD KE TERI AMMY KA MANG BHARUNGA 🤣🍌🍑",
    "TERI BHEN KO UTHA KE SALWAR KE SATH HI PELUNGA 🤣🍑",
    "BHAG MADARCHOD TERI AMMY TOH NUKKAD KI R🍑NDI HAI RE 🤣",
    "BIJILI KE BULB SE PAIDA HUA CHUJA HAI TU TERI AMMY BIJILI KA BULB APNE BHOXDE ME DAL KE TUJHR PAIDA KI THI 🤖🌀🍑 ",
    "AATE KI CHAKKI ME DAL KE TERE PURE KHANDAN KA BHUNSA NIKAL DUNGA SAMJHA KYA G@NDU😈🍌🤣🍑",
    "🇹 ERI 🇧 HEN 🇰 A 🇨 HOOCHI 🇵 AKAD 🇰 E 🇩 ANTON 🇸 E 🇵 ELUNGA 🇰 ACHA 🇰 ACH 🇰 ACH 🇰 ACH😂🧟",
    "ULTA LATKA KE PICHHWADE PE ITNA LAAT MARUNGA NA RAAT BHAR DARD KI KASH MAKASH SE SO NAHI PAOGE BETE 🤣🍑🍌",
    "UTHA UTHA KE PATKUNGA TERE BAAP KO BHI AUR TUJE BHI TERA PURA KHANDAN BICH ROAD PE MUJRA KARTA HUA DIKHAI DEGA AGAR MAI APNE PE AAGAYA TOH 😑♥️🤣",
    "𝐀𝐌𝐀𝐙𝐎𝐍 𝐒𝐄 𝐎𝐑𝐃𝐄𝐑 𝐊𝐈𝐘𝐄 𝐇𝐔𝐀 𝐑@𝐍𝐃𝐈 𝐊𝐈 𝐀𝐔𝐋𝐀𝐀𝐃",
    "𝐂𝐇𝐇𝐈𝐏𝐊𝐀𝐋𝐈 𝐉𝐀𝐈𝐒𝐄 𝐃𝐄𝐄𝐖𝐀𝐋 𝐏𝐄 𝐂𝐇𝐀𝐃𝐇 𝐊𝐄 𝐓𝐄𝐑𝐄 𝐁𝐀𝐀𝐏 𝐊𝐄 𝐌𝐔𝐇 𝐌𝐄 𝐌𝐎𝐎𝐓 𝐃𝐔𝐍𝐆𝐀 😂",
    "T3RIIII AMMY KEEE JH@NTAAA KO PAKADD KR BUILDING SE LATKA DUNGA 🤣🤣 WAH WAH WAH !!! 🤣",
    "DARWAJE KE KONE ME TERI ᗩᗰᗰY Kᗩ ᑕᕼOOᑕᕼI 𝗟𝗔𝗚𝗔 𝗞𝗘 ᵈᵃʳʷᵃʲᵃ ᵇᵃⁿᵈ 🅚︎🅐︎🅡︎ 🅓︎🅤︎🅝︎🅖︎🅐︎",
    "FORTUNE LAGA KE PELUNGA TERI MA KE CHOOT KO CHUS JAUNGA 😂",
    "GAND ME SARSO KE TAIL KE SATH TEZAB DAL DUNGA TERE JB TU MARWANE AYEGA MUJHSE 😂",
    "SINDOORI CHOOT WALI RANDI KE BACCHE BHENCHOD 🤣😂",
    "PAODAAN KI SHAKAL KE G@NDU SALE 👹😹",
    "MASK PEHNA KE APNE LODE KO TERI BEHEN KE CHOOXT ME DAAL DUNGA 🤣👀👅",
    "YAAD AATI HAI TERI JB JB MARTA HUN MOOTH TERI MA KI CHUT TERI MA KI CHUT 🤣👌👅",
    "BOLTI THI SATH NIBHAUNGI YE RISHTA HAI ATUT , CHHOR KE CHALI GYI 2 MAHINE BAD USKI MA KI CH00T USKI MA KI CH00T 👅👌",
    "LOCKDOWN ME MANGYA THA TUNE MUNHSE KITKAT AUR POLICE NE DIYA MUJE SUT , TERI MA KI CHUT TERI MA KI CHUT 🤣👅",
    "BATA KE CHAPPLE SE MAR MAR KE MUH LAL KARDUNGA BHOSADI KE 👹😹🤣👅❣️",
    "VIMAL KHANE WALE RANDI KE BACCHE MADARCHOD !!? 😂🤣😹👹",
    "BABY BABY BOLKE LIYE TUNE MUJHE LOOT BHAG TERI MA KI CHUT TERI MA KI CHUT",
    "TERI BAHEN KI CHUT MEI APPLE KA 18W WALA CHARGER 🔥🤩",
    "TERI AMMY KS BLOWJ FAAD KE USKE CHOOCHI PE APNA LODA MARUNGA AUR KACHA KACH PELUNGA 🤣",
    "TERI AMMY KO THAR ME GHUMA KE IMPRESS KARKE FIR USI THAR KE BONAT PE LETA KE USKI GULABI CHUT LUNGA 👻",
    "JH@NT KE PISSU SALE LODU KAHI KE R@NDI KI OLAD 🤣",
    "TERI BHEN KO SARDI KI THANDI ME CHHAT PE NANGA KARKE CHODUNGA MADARCHOD 👌🤣🤣🤣🤣🤣👅😈",
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧 𝗦𝗕𝗦𝗘𝗘𝗘𝗘𝗘 𝗦𝗘𝗘𝗫𝗫𝗫𝗬𝗬𝗬𝗬𝗬 😘💋",
    "𝗧𝗘𝗜𝗥𝗥𝗥𝗥 𝗠𝗔𝗔𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔𝗔𝗔 𝗥𝗔𝗣𝗘𝗘𝗘𝗘𝗘𝗘 𝗞𝗥𝗞𝗘𝗘𝗘𝗘 𝗕𝗛𝗔𝗚𝗚𝗚𝗚𝗚𝗚 𝗝𝗔𝗔𝗔𝗔𝗨𝗡𝗚𝗔𝗔𝗔 👅🤣🤣",
    "𝗧𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔𝗔 𝗣𝗢𝗥𝗡 𝗛𝗨𝗕 𝗠𝗔𝗜𝗜 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗙𝗔𝗔𝗗𝗡𝗘 𝗔𝗔𝗚𝗬𝗘 𝗛𝗔𝗜 𝗕𝗘𝗧𝗜𝗖𝗛𝗢𝗗⚡️⚡️⚡️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗖𝗛𝗨𝗧 𝗙𝗔𝗧𝗘𝗚𝗜 𝗞𝗜𝗨𝗞𝗜 𝗦𝗕𝗦𝗘 𝗙𝗔𝗦𝗧𝗘𝗦𝗧 𝗕𝗢𝗧 𝗔𝗔𝗚𝗔𝗬𝗔 𝗛𝗔𝗜 𝗧𝗚 𝗣𝗘😈😈⚡️",
    "𝗧𝗥𝗜𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗟𝗘𝗞𝗥 𝗕𝗛𝗔𝗚 𝗝𝗔𝗔𝗨𝗡𝗚𝗔 🤣💋𝗔𝗨𝗥 𝗫𝗫𝗫 𝗕𝗔𝗡𝗔𝗨𝗡𝗚𝗔 🤤",
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗫𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗫𝗛𝗢𝗗𝗧𝗘 𝗫𝗛𝗢𝗗𝗧𝗘 𝗕𝗔𝗫𝗫𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢 𝗝𝗔𝗔𝗬𝗘𝗡𝗚𝗘 🤣🔥",
    "𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗨𝗗𝗘𝗚𝗜 𝗕𝗘𝗧𝗘 𝗖𝗛𝗨𝗗 𝗝𝗔𝗬𝗘𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧 𝗙𝗔𝗧𝗘𝗚𝗜 𝗔𝗕💦💦🍆🍑😂",
    "𝗧𝗥𝗜𝗜 𝗕𝗔𝗔𝗔𝗣 𝗫𝗛𝗔𝗞𝗞𝗔 𝗛 𝗞𝗬𝗔 ??",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗢𝗗𝗞𝗘 𝗙𝗔𝗥𝗔𝗔𝗥 𝗛𝗢 𝗚𝗔𝗬𝗜😘😂😂😂",
    "𝗧𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗫𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗫𝗛𝗨𝗧 𝗙𝗔𝗧 𝗝𝗔𝗔𝗬𝗘𝗚𝗜𝗜 🤤🤣🔥",
    "𝗔𝗣𝗡𝗜𝗜𝗜𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢𝗢 𝗣𝗔𝗜𝗗 𝗚𝗜𝗥𝗟𝗟𝗟 𝗕𝗡𝗔 𝗗𝗘𝗘𝗘𝗘 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗘 𝗚𝗨𝗕𝗕𝗔𝗥𝗘 𝗣𝗛𝗘𝗞 𝗞𝗘 𝗠𝗦𝗥𝗨𝗡𝗚𝗔 𝗧𝗨𝗝𝗛𝗘😂🤤💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗔𝗜 𝗦𝗔𝗥𝗜𝗬𝗔𝗟 𝗗𝗔𝗔𝗟 𝗞𝗘 𝗖𝗛𝗨𝗧 𝗦𝗘 𝗕𝗔𝗛𝗔𝗥 𝗡𝗜𝗞𝗔𝗟𝗨𝗡𝗚𝗔 💦🍆🍑😈",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗚𝗕 𝗥𝗢𝗔𝗗 𝗞𝗜 𝗦𝗔𝗦𝗧𝗜 𝗥𝗔𝗡𝗗𝗜 𝗛𝗔𝗜 𝗕𝗘𝗧𝗘😂💋🍑🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗕𝗣 𝗦𝗛𝗢𝗢𝗧 𝗞𝗔𝗥𝗞𝗘 𝗣𝗢𝗥𝗡𝗛𝗨𝗕 𝗣𝗘 𝗗𝗔𝗟𝗨𝗡𝗚𝗔 😝🍑😂🔥",
    "𝗔𝗔𝗝 𝗧𝗘𝗥𝗔 𝗞𝗛𝗔𝗡𝗗𝗔𝗡 𝗫𝗛𝗨𝗗𝗘𝗚𝗔 💦🍆🍑",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗣𝗘 𝗝𝗛𝗨𝗟𝗘𝗚𝗜🍆🍑😁",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗞𝗢 𝗗𝗔𝗗𝗗𝗬 𝗕𝗢𝗟𝗧𝗜 𝗛𝗔𝗜😂🤤🍑💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔 𝗚𝗔𝗡𝗚 𝗕𝗔𝗡𝗚 𝗞𝗥𝗔 𝗗𝗨𝗡𝗚𝗔 🤣🔥💋 ",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗨𝗦𝗜 𝗞𝗜 𝗫𝗛𝗨𝗧 𝗞𝗔𝗔𝗟𝗜 𝗔𝗬𝗘 𝗛𝗔𝗜 𝗧𝗘𝗥𝗜 𝗧𝗢𝗛 𝗛𝗨𝗠𝗡𝗘 𝗚𝗔𝗔𝗡𝗗 𝗙𝗔𝗔𝗗 𝗗𝗔𝗔𝗟𝗜💦🍆🍑🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗖𝗔𝗥 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗞𝗜𝗗𝗗 🤣🔥",
    "𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗞𝗢 𝗠𝗔𝗔𝗔𝗥 𝗗𝗨𝗡𝗚𝗔𝗔𝗔𝗔 𝗕𝗔𝗫𝗫𝗛𝗘 🤣👅 ",
    "𝗧𝗘𝗥𝗜 𝗚𝗔𝗔𝗡𝗗 𝗙𝗧 𝗟𝗘 𝗧𝗨𝗞𝗗𝗘 𝗛𝗢 𝗚𝗔𝗬𝗘 𝗖𝗛𝗔𝗔𝗥 𝗔𝗕𝗘 𝗖𝗛𝗔𝗟 𝗡𝗜𝗞𝗔𝗟 𝗪𝗔𝗥𝗡𝗔 𝗜𝗧𝗡𝗔 𝗠𝗔𝗥𝗨𝗡𝗚𝗔 𝗞𝗜 𝗛𝗢 𝗝𝗔𝗜𝗘𝗚𝗔 𝗧𝗘𝗥𝗔 𝗛𝗔𝗔𝗟 𝗕𝗘𝗛𝗔𝗟😂😎😈⚡️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔𝗔𝗔 𝗠𝗘𝗥𝗞𝗢 𝗗𝗔𝗗𝗗𝗬 𝗡𝗔𝗔𝗠 𝗦𝗘 𝗣𝗨𝗞𝗔𝗥𝗘𝗘𝗘😌😂😈🍑",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗦𝗕𝗦𝗘 𝗔𝗖𝗖𝗛𝗜 𝗣𝗔𝗜𝗗 𝗚𝗜𝗥𝗟 🤤💋",
    "𝗔𝗕𝗘 𝗔𝗔𝗝 𝗧𝗘𝗥𝗜 𝗚𝗔𝗔𝗡𝗗𝗔𝗜 𝗟𝗘𝗗 𝗙𝗜𝗧 𝗞𝗔𝗥𝗨𝗡𝗚𝗔 𝗙𝗜𝗥 𝗧𝗘𝗥𝗜 𝗧𝗔𝗔𝗡𝗗 𝗖𝗛𝗔𝗠𝗔𝗞 𝗨𝗧𝗛𝗘𝗚𝗜😂🍆🍑",
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗦𝗔𝗦𝗧𝗔 𝗦𝗣𝗔𝗠🤣 𝗕𝗢𝗧 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗦𝗣𝗔𝗠 𝗞𝗥𝗨𝗡𝗚𝗔 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗔𝗨𝗗𝗘 𝗣𝗘 𝗙𝗜𝗦𝗔𝗟 𝗞𝗔𝗥 𝗚𝗜𝗥 𝗚𝗔𝗬𝗜 𝗔𝗨𝗥 𝗣𝗥𝗘𝗚𝗡𝗔𝗡𝗧 𝗛𝗢 𝗚𝗔𝗬𝗜😂🍑🍆💋",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗡𝗘 𝗠𝗘𝗥𝗔 𝗡𝗨𝗠𝗕𝗘𝗥 𝗗𝗔𝗗𝗗𝗬 𝗡𝗔𝗠𝗘 𝗦𝗘 𝗦𝗔𝗩𝗘 𝗞𝗔𝗥 𝗥𝗞𝗛𝗔 𝗛𝗔𝗜🙈👻😈💋",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗢 𝗟𝗔𝗨𝗗𝗘 𝗣𝗘 𝗡𝗔𝗖𝗛𝗔𝗨𝗡𝗚𝗔 😂🍆🍑",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗗𝗜𝗘 𝗛𝗔𝗥𝗗 𝗙𝗔𝗡 𝗛𝗔𝗜 👻🙈😂💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗦𝗘 𝗣𝗘𝗛𝗟𝗘 3 𝗗𝗜𝗟𝗗𝗢 𝗔𝗨𝗥 𝗘𝗞 𝗩𝗜𝗕𝗥𝗔𝗧𝗢𝗥 𝗨𝗦𝗘 𝗞𝗔𝗥𝗧𝗜 𝗧𝗛𝗜😂🍑👻🍆💦",
    "𝗔𝗣𝗡𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗫𝗛𝗨𝗧 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗭𝗢𝗠𝗔𝗧𝗢 𝗠𝗔𝗜 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔 💋🤤🥵",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗔 𝗣𝗔𝗣𝗔 𝗞𝗔 𝗟𝗨𝗡𝗗 𝗠𝗔𝗜 𝗗𝗨𝗠 𝗡𝗔𝗛𝗜 𝗧𝗛𝗔 𝗜𝗦𝗟𝗜𝗬𝗘 𝗠𝗘𝗥𝗘 𝗦𝗘 𝗖𝗛𝗨𝗗𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗡𝗘 𝗧𝗨𝗝𝗛𝗘 𝗝𝗔𝗡𝗔𝗠 𝗗𝗜𝗬𝗔🍆💦🍑😂👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗔𝗠𝗔𝗭𝗢𝗡 𝗠𝗔𝗜 𝗦𝗘𝗟𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 50 𝗠𝗔𝗜 🤤💋😊❤️",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗖𝗢𝗟𝗔𝗧𝗘 𝗙𝗟𝗔𝗩𝗢𝗨𝗥 𝗣𝗔𝗦𝗔𝗡𝗗 𝗛𝗔𝗜👻🍆🍑😂",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗘 𝗚𝗛𝗔𝗥 𝗞𝗘 𝗣𝗔𝗔𝗦 𝗪𝗔𝗟𝗘 𝗗𝗨𝗞𝗔𝗡 𝗠𝗔𝗜 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 200 𝗞𝗘 𝗕𝗛𝗔𝗩 𝗕𝗜𝗞 𝗥𝗛𝗜 𝗛𝗔𝗜😂👻🍆🍑",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗫𝗛𝗨𝗧 𝗦𝗕𝗦𝗘 𝗦𝗘𝗫𝗫𝗬 𝗛 𝗠𝗔𝗗𝗔𝗥𝗫𝗝𝗢𝗗 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗖𝗛𝗨𝗧 𝗙𝗔𝗧 𝗞𝗘 𝗛𝗢 𝗚𝗔𝗬𝗘 𝗧𝗨𝗞𝗗𝗘 𝗖𝗛𝗔𝗔𝗥😂🍑🍆👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧 𝗙𝗔𝗔𝗔𝗗 𝗞𝗘 𝗦𝗔𝗕 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗡𝗨𝗡𝗚𝗔 🤤💋🔥",
    "𝗔𝗡𝗗𝗜 𝗠𝗔𝗡𝗗𝗜 𝗦𝗔𝗡𝗗𝗜 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗫𝗛𝗨𝗧𝗧𝗧😂👻🍆🍑",
    "𝗔𝗔𝗨𝗞𝗔𝗔𝗧 𝗠𝗔𝗜 𝗥𝗘𝗛 𝗞𝗔𝗥 𝗕𝗔𝗔𝗧 𝗞𝗥 𝗟𝗜𝗬𝗔 𝗞𝗥 𝗕𝗔𝗫𝗫𝗛𝗘 𝗪𝗔𝗥𝗡𝗔 𝗠𝗔𝗔𝗔 𝗫𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 🤣🔥🖕",
    "𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗗𝗘𝗞𝗛𝗞𝗥 𝗗𝗔𝗘 𝗚𝗔𝗬𝗜 𝗗𝗔𝗥𝗞𝗘 𝗨𝗦𝗡𝗘 𝗗𝗜𝗬𝗔 𝗠𝗨𝗧 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗔𝗟𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧😂🍑👻",
    "𝗛𝗔𝗥𝗘 𝗛𝗔𝗥𝗘 𝗝𝗛𝗔𝗗𝗜𝗬𝗢 𝗠𝗘 𝗕𝗔𝗗𝗔 𝗕𝗔𝗗𝗔 𝗚𝗛𝗢𝗦𝗟𝗔 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂🍑🍆👻",
    "𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗗𝗘𝗞𝗛𝗞𝗥 𝗗𝗔𝗘 𝗚𝗔𝗬𝗜 𝗗𝗔𝗥𝗞𝗘 𝗨𝗦𝗡𝗘 𝗗𝗜𝗬𝗔 𝗠𝗨𝗧 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗔𝗟𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧😂🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗟𝗘𝗞𝗘 𝗕𝗛𝗔𝗚 𝗝𝗔𝗔𝗨𝗡𝗚𝗔  🤤💋𝗔𝗨𝗥 𝗞𝗔𝗟 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔  𝗗𝗜𝗞𝗛𝗘𝗚𝗜 𝗖𝗜𝗗 𝗠𝗔𝗜 🤣🔥",
    "𝗔𝗥𝗘 𝗕𝗘𝗧𝗘 𝗬𝗔𝗦𝗛 𝗔𝗨𝗥 𝗟𝗨𝗖𝗜𝗙𝗘𝗥 𝗞𝗘 𝗣𝗜𝗥𝗢 𝗕𝗢𝗧 𝗦𝗘 𝗖𝗛𝗨𝗗 𝗚𝗔𝗬𝗔 𝗧𝗨 𝗡𝗜𝗞𝗟 𝗪𝗔𝗥𝗡𝗔 𝗔𝗨𝗥 𝗖𝗛𝗨𝗗𝗘𝗚𝗔 𝗕𝗘𝗧𝗘😁🍆🔥🍑",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧 𝗟𝗘𝗔𝗞 𝗞𝗔𝗥 𝗥𝗛𝗜 𝗛𝗔𝗜 𝗠𝗔𝗜 𝗣𝗟𝗨𝗠𝗕𝗘𝗥 𝗛𝗨 𝗥𝗨𝗞 𝗧𝗛𝗜𝗞 𝗞𝗔𝗥 𝗗𝗨𝗡𝗚𝗔😂🍆🍑👻",
    "𝗔𝗡𝗗𝗜𝗜 𝗠𝗔𝗡𝗗𝗜𝗜𝗜 𝗦𝗛𝗔𝗡𝗗𝗜𝗜𝗜 𝗔𝗚𝗔𝗥 𝗗𝗨𝗦𝗠𝗔𝗡 𝗟𝗢𝗚 𝗥𝗘𝗣𝗟𝗬 𝗞𝗜𝗬𝗔 𝗧𝗢𝗛 𝗨𝗦𝗞𝗔 𝗠𝗔 𝗕𝗛𝗘𝗡 𝗥𝗔𝗡𝗗𝗜𝗜 😅😅😒",
    "𝗧𝗨 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗖𝗔𝗥 𝗖𝗛𝗔𝗗𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 🤣🔥",
    "𝗔𝗥𝗘 𝗝𝗬𝗔𝗗𝗔 𝗨𝗗 𝗠𝗔𝗧 𝗪𝗔𝗥𝗡𝗔 𝗣𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗔 𝗞𝗛𝗢𝗣𝗗𝗔 𝗔𝗨𝗥 𝗝𝗬𝗔𝗗𝗔 𝗕𝗢𝗟𝗘𝗚𝗔 𝗧𝗢𝗛 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗔 𝗕𝗚𝗢𝗦𝗗𝗔😂🍆🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗦𝗔𝗕 𝗞𝗢 𝗕𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣✌️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗢 𝗞𝗜𝗗𝗡𝗔𝗣 𝗞𝗥𝗞𝗘 𝗡𝗔𝗡𝗚𝗔 𝗥𝗢𝗔𝗗 𝗣𝗘 𝗫𝗛𝗢𝗗 𝗗𝗨𝗡𝗙𝗔 🤣🤤🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗬𝗬𝗜𝗔 𝗧𝗢𝗛 𝗞𝗔𝗟𝗔𝗣𝗡𝗘 𝗟𝗔𝗚𝗜 🤣🥺",
    "𝗔𝗕𝗘 𝗞𝗜𝗗 𝗕𝗛𝗢𝗞 𝗠𝗔𝗧 𝗝𝗬𝗔𝗗𝗔 𝗪𝗔𝗥𝗡𝗔 𝗔𝗡𝗗𝗔𝗥 𝗦𝗘 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗞𝗛𝗢𝗞𝗟𝗔 𝗔𝗨𝗥 𝗔𝗕 𝗞𝗨𝗖𝗛 𝗕𝗢𝗟𝗔 𝗧𝗢𝗛 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂🍆🍑😜👻",
    "𝗧𝗘𝗥𝗜𝗜 𝗠𝗔 𝗠𝗘𝗥𝗘 𝗞𝗔𝗕𝗝𝗘 𝗠𝗔𝗜 𝗛𝗔𝗜 𝗟𝗘𝗡𝗔 𝗠𝗔𝗡 𝗛𝗔𝗜 𝗧𝗢𝗛 𝗣𝗔𝗬 10000000 🤣🤣🤣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗠𝗢𝗔𝗡 𝗣𝗘 𝗕𝗛𝗜 𝗛𝗜𝗟𝗔 𝗟𝗘𝗧𝗔 𝗛𝗨 𝗜𝗧𝗡𝗜 𝗛𝗢𝗧 𝗛𝗔𝗜 𝗩𝗢𝗛🙈😂👻🍆",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜𝗧𝗡𝗜 𝗛𝗢𝗧 𝗛𝗔𝗜 𝗬𝗔𝗔𝗥 𝗠𝗔𝗡 𝗞𝗥𝗧𝗔 𝗛𝗔𝗜 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨 𝗞𝗜 𝗔𝗨𝗥 𝗞𝗢𝗜 𝗖𝗛𝗢𝗗 𝗡𝗔 𝗣𝗔𝗬𝗘 𝗨𝗦𝗞𝗢😂🍑🍆👻",
    "𝗧𝗔𝗔𝗥𝗔𝗞 𝗠𝗘𝗛𝗧𝗔 𝗞𝗔 𝗨𝗟𝗧𝗔 𝗖𝗛𝗔𝗦𝗠𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗔𝗗𝗔 𝗕𝗔𝗗𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂👻🍑🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗣𝗧𝗔𝗞 𝗞𝗘 𝗫𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 𝗞𝗜 𝗣𝗔𝗧𝗔 𝗩 𝗡𝗛𝗜 𝗖𝗛𝗔𝗟𝗘𝗚𝗔 𝗔𝗨𝗥 𝗕𝗔𝗫𝗫𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜 🤣🤤🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗢𝗬𝗢 𝗟𝗘 𝗝𝗔𝗔𝗞𝗥 𝗣𝗘𝗟𝗨𝗡𝗚𝗔 𝗜𝗧𝗡𝗔 𝗞𝗜 𝗞𝗔𝗕𝗛𝗜 𝗖𝗛𝗨𝗧 𝗡𝗔𝗛𝗜 𝗗𝗜𝗞𝗛𝗔 𝗣𝗔𝗬𝗘𝗚𝗜 𝗙𝗜𝗥😂🍆👻🍑💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗔𝗜 𝗜𝗡𝗦𝗧𝗔𝗚𝗥𝗔𝗠 𝗞𝗔 𝗥𝗘𝗘𝗟 𝗟𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 🤤🙈💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗧𝗜𝗞𝗧𝗢𝗞 𝗞𝗜 𝗦𝗔𝗦𝗧𝗜 𝗥𝗔𝗡𝗗𝗜 𝗛𝗔𝗜😂🍆💋",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗔𝗗𝗔 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗔𝗠𝗔𝗭𝗢𝗡 𝗠𝗔𝗜 𝗦𝗘𝗟𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 1 𝗠𝗔𝗜 🥺🤣💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗗𝗨𝗕𝗔𝗜 𝗠𝗔𝗜 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔 𝗔𝗨𝗥 𝗫𝗛𝗨𝗗𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗨𝗦𝗞𝗔 𝗣𝗥𝗜𝗡𝗖𝗘 𝗦𝗘 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗣𝗥𝗜𝗩𝗔𝗧𝗘 𝗩𝗜𝗟𝗟𝗔 𝗟𝗘 𝗝𝗔𝗔𝗞𝗥 𝗣𝗘𝗟𝗨𝗡𝗚𝗔 😂🍆💋🍑",
    "𝗜 𝗙𝗨𝗖𝗞𝗘𝗗 𝗨𝗥 𝗠𝗢𝗠 😂🍆",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗪𝗜𝗟𝗟 𝗦𝗨𝗖𝗞 𝗠𝗬 𝗗𝗜𝗖𝗞😂🍆🍑",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗔𝗡𝗗 𝗦𝗜𝗦𝗧𝗘𝗥 𝗜𝗦 𝗩𝗘𝗥𝗬 𝗛𝗢𝗧𝗧 𝗠𝗔𝗡 𝗦𝗛𝗘 𝗦𝗨𝗖𝗞'𝗦 𝗠𝗬 𝗗𝗜𝗖𝗞 𝗘𝗩𝗘𝗥𝗬𝗗𝗔𝗬🙈🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗫𝗫 𝗩𝗜𝗥𝗔𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗕𝗔𝗫𝗖𝗛𝗘 🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗨𝗗𝗞𝗘 𝗗𝗔𝗥 𝗚𝗔𝗬𝗜 𝗬𝗔𝗔𝗥💦👻🙈",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗔 𝗠𝗜𝗗𝗗𝗟𝗘 𝗙𝗜𝗡𝗚𝗘𝗥 𝗡𝗔𝗜𝗟 𝗡𝗔𝗛𝗜 𝗛𝗔𝗜😂👻🍑🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔 𝗫𝗛𝗨𝗗𝗔𝗜 𝗔𝗟𝗜𝗩𝗘 𝗣𝗜𝗖 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 🤤😂",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗖𝗛𝗢𝗗𝗧𝗘 𝗪𝗔𝗞𝗧 𝗬𝗢𝗨𝗧𝗨𝗕𝗘 𝗣𝗘 𝗟𝗜𝗩𝗘 𝗞𝗔𝗥𝗨𝗡𝗚𝗔😂🍆🍑💦",
    "𝗔𝗕𝗜 𝗩 𝗧𝗜𝗠𝗘 𝗛 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗣𝗔𝗣𝗔 𝗕𝗢𝗟 𝗔𝗨𝗥 𝗟𝗨𝗡𝗗 𝗣𝗞𝗔𝗗 🤣🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘 𝗫𝗛𝗨𝗧  𝗠𝗔𝗜 𝗥𝗢𝗖𝗞𝗘𝗧 𝗟𝗔𝗨𝗡𝗖𝗛 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗡𝗔𝗦𝗔 𝗪𝗔𝗟𝗔 🤤💋😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗔𝗥𝗔𝗠 𝗚𝗔𝗥𝗔𝗠 𝗧𝗘𝗟 🥺🤣💋",
    "𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗔𝗔𝗚𝗬𝗘 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗞𝗔𝗟𝗔𝗣 𝗠𝗧 𝗔𝗕 🤣🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗘𝗞 𝗔𝗨𝗥 𝗫𝗛𝗨𝗧 𝗗𝗔𝗟𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗥𝗡𝗗𝗜 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗣𝗘 𝗖𝗥𝗜𝗖𝗞𝗘𝗧 𝗞𝗛𝗘𝗟𝗡𝗚𝗘 🤣😱",
    "𝗨𝗙𝗙 𝗖𝗛𝗨𝗗 𝗚𝗔𝗬𝗔 𝗕𝗘𝗧𝗔 𝗔𝗕 𝗕𝗛𝗢𝗞 𝗖𝗛𝗨𝗧𝗜𝗬𝗔 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗟𝗔𝗗𝗡𝗘 𝗔𝗔𝗬𝗔 𝗧𝗛𝗔 𝗡𝗔😂🍆🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗣𝗨𝗦𝗦𝗬 𝗖𝗛𝗔𝗧𝗨𝗡𝗚𝗔 𝗕𝗘𝗧𝗘😂🍑🍆🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗥𝗔𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗞𝗜 𝗠𝗔𝗡𝗔𝗚𝗘𝗥 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗞𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗟𝗢 𝗣𝗔𝗥 𝗣𝗔𝗜𝗦𝗘 𝗗𝗘𝗧𝗘 𝗝𝗔𝗔𝗡𝗔 🤣🔥🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗙𝗔𝗡 𝗛𝗔𝗜😍👻💋🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗞𝗘 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔𝗔𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣🔥",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗕 𝗣𝗔𝗣𝗔 𝗚𝗔𝗟𝗧𝗜 𝗛𝗢 𝗚𝗔𝗬𝗜 𝗠𝗔𝗔𝗙 𝗞𝗔𝗥𝗗𝗢😁🍑🍆👻",
    "𝗔𝗣𝗡𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗚𝗔𝗔𝗔𝗡𝗗 𝗗𝗘𝗗𝗢 🥺 𝗧𝗛𝗢𝗗𝗜 𝗗𝗘𝗥 𝗣𝗘𝗟 𝗞𝗘 𝗗𝗘𝗧𝗔 𝗛𝗨 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗛𝗔𝗥 𝗕𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 𝗟𝗢𝗗𝗘 🤤💋",
]


RRAID = [
    "𝗬𝗛𝗔 𝗔𝗔 𝗝𝗔𝗢 𝗗𝗘𝗔𝗥 ❤️👀✨ -\nhttps://t.me/+aK5MFyqERPo4MzE1",
]



PORMS = [
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
]
